image: 'abhishekf5/maven-abhishek-docker-agent:v1'

variables:
  SONAR_HOST_URL: http://34.203.223.11:9000
  SONAR_LOGIN: ${SONAR_LOGIN}

# Define the default working directory for the pipeline
before_script:
  - cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

stages:   
  - build
  - test
  - sonarqube
  - deploy

build-job:  
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package

unit-test-job:  
  stage: test  
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - mvn test

code-quality-job:  
  stage: sonarqube 
  script:
    - echo "scanning code"
    -  mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN}

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
